#It should be possible to open a bank account with an initial deposit and credit line.
POST http://localhost:8081/accounts
Content-Type: application/json

{
  "initialBalance": 100,
  "owner": "Dan"
}

> {%
  client.global.set("accountId", response.body);
%}

###
GET http://localhost:8082/accounts/{{accountId}}
Accept: application/json

###

POST http://localhost:8081/accounts/{{accountId}}/creditLines
Content-Type: application/json

{
  "amount": 1000
}


###
#It should be possible to retrieve the current account balance of a given bank account.

PUT http://localhost:8081/accounts/debit/{{accountId}}
Content-Type: application/json

{
  "amount": 1000
}

###



#It should be possible to test if a pending debit payment would exceed the overdraft limit of that bank account.
#It should be possible to get a list of all transactions booked of a given bank account since a given calendar date.
#It should be possible to receive a list of all bank accounts in the red, i.e., whose account balance is lower than zero.
GET http://localhost:8082/accounts/0a60d086-561e-4ee6-a489-427d07665988
Accept: application/json

<> 2022-11-28T113736.200.json
